### PR TITLE
A new field Session Number appears along Ratings and Reviews

### PR DESCRIPTION
**Pull request by navneel99**
Now, alongside one's ratings and reviews in the profile, a separate column for Session Number appears.

### CODE REVIEW

**Comment by navneel99** [comment]
Next, I would create session wise ratings.

**Comment by navneel99** [comment]
Some bugs have appeared

**Comment by DivyanshuSaxena** [comment]
Can you elaborate on the use of this PR?

**Comment by navneel99** [comment]
This PR was created to show ratings across sessions.
A user can see the ratings of the current session, and also see the cumulative ratings of the past sessions.

**Pull request closed without merging**
